version: '3'

services:

  gloo:
    image: "${GLOO_REPO:-quay.io/solo-io}/gloo:${GLOO_VERSION:-1.3.17}"
    working_dir: /
    command:
    - "--dir=/data/"
    volumes:
    - ./data:/data/
    ports:
    - "9977:9977"
    restart: always

  gateway:
    image: "${GLOO_REPO:-quay.io/solo-io}/gateway:${GLOO_VERSION:-1.3.17}"
    working_dir: /
    command:
    - "--dir=/data/"
    volumes:
    - ./data:/data/
    restart: always

  gateway-proxy:
    image: ${GLOO_REPO:-quay.io/solo-io}/gloo-envoy-wrapper:${GLOO_VERSION:-1.3.17}
    entrypoint: ["envoy"]
    command: ["-c", "/config/envoy.yaml", "--disable-hot-restart"]
    volumes:
    - ./data/envoy-config.yaml:/config/envoy.yaml:ro
    ports:
    - "8080:8080"
    - "8443:8443"
    - "19000:19000"
    restart: always

  #extauth:
  #  image: quay.io/solo-io/extauth-ee:1.3.0
  #  environment:
  #  - SERVICE_NAME=ext-auth
  #  - GLOO_ADDRESS=gloo:9977
  #  - SERVER_PORT=8083
  #  ports:
  #  - "8083:8083"


 # example application, the swagger petstore
  petstore:
    image: soloio/petstore-example:latest
    ports: 
    - "8090:8080"
    restart: always
